image: Ubuntu1804 #Образ для сборки
stack: node 16 # Окружение
branches:
  only:
    - main # Ветка git
cache: node_modules # кеширование
install:
  - npm install # Команда установки зависимостей
build: off
test_script:
  - npm run lint && npm test # Скрипт сборки